name: CI / CD for Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Testing the App
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building the Application
        run: npm run build 