name: Issues - Create Only
on:
  issues:
    types: opened
 
jobs:
  preparing:
    runs-on: ubuntu-latest
    steps:
      - name: Get Context Github - event
        run: echo "${{ toJson(github.event) }}"
